### ISSUE TITLE
Add concept of double-line breakouts

### ISSUE THREAD

**Issue by makenosound** [icelab/draft-js-block-breakout-plugin#1]
Most blocks that wouldn’t require a single-line break out could do with a double-line one. I.e., Enter two empty blocks in a row.

**Comment by terencechow** [comment]
+1 this is the common behaviour of other word processors

**Comment by makenosound** [comment]
Closed by @Rosey’s contribution here https://github.com/icelab/draft-js-block-breakout-plugin/pull/9 and released as v1.0.3.
