### ISSUE TITLE
Breakout doesn't seem to be working in latest beta 2.0.0-beta6

### ISSUE THREAD

**Issue by stevewillard** [icelab/draft-js-block-breakout-plugin#3]
I can try to provide more details if it helps, but it doesn't seem like breaking out is working. Things were working in version 2.0.0-beta5 for me.

**Comment by makenosound** [comment]
@stevewillard Ta for letting me know, will see if I can test it out later in the week.

**Comment by davidgeilfus** [comment]
@stevewillard @makenosound Did you find a solution? Thank you in advance!

**Comment by stevewillard** [comment]
Sorry, no, I haven't. I may have time next week to look more into it.

**Comment by makenosound** [comment]
@stevewillard @davidgeilfus Have cut 1.0.0 (thanks to @sugarshin) which I think should solve this issue. Mind giving it a spin?

**Comment by stevewillard** [comment]
It works! Thank you so much. Closing this out.
